# Generated by Django 3.1.7 on 2021-03-16 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Training', 'Training')], default='Open', max_length=10)),
                ('code_language', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript')], default='Python', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='TrackingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked_in_day', models.IntegerField(default=1)),
                ('date_added', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>')),
                ('hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours.projectworked')),
            ],
            options={
                'verbose_name_plural': 'Tracking Hours',
            },
        ),
    ]
