# Generated by Django 3.1.7 on 2021-03-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoursWorked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Training', 'Training')], default='Open', max_length=10)),
                ('code_language', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript')], default='Python', max_length=10)),
                ('hours_worked_in_day', models.IntegerField(default=1)),
                ('date_added', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>')),
            ],
        ),
    ]
